import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "upload.wikimedia.org" },
      { protocol: "https", hostname: "www.abc.com.py" },
      { protocol: "http", hostname: "www.abc.com.py" },
      { protocol: "https", hostname: "abc.com.py" },
      { protocol: "http", hostname: "abc.com.py" },
      { protocol: "https", hostname: "apf.org.py" },
      { protocol: "http", hostname: "apf.org.py" },
      { protocol: "https", hostname: "www.apf.org.py" },
      { protocol: "http", hostname: "www.apf.org.py" },
      { protocol: "https", hostname: "sport8.com.py" },
      { protocol: "https", hostname: "www.sport8.com.py" },
      { protocol: "https", hostname: "www.lanacion.com.py" },
      { protocol: "http", hostname: "www.lanacion.com.py" },
      { protocol: "https", hostname: "lanacion.com.py" },
      { protocol: "http", hostname: "lanacion.com.py" },
      { protocol: "https", hostname: "www.espn.com.py" },
      { protocol: "http", hostname: "www.espn.com.py" },
      { protocol: "https", hostname: "espn.com.py" },
      { protocol: "http", hostname: "espn.com.py" },
      { protocol: "https", hostname: "telefuturo.com.py" },
      { protocol: "http", hostname: "telefuturo.com.py" },
      { protocol: "https", hostname: "www.telefuturo.com.py" },
      { protocol: "http", hostname: "www.telefuturo.com.py" },
      { protocol: "https", hostname: "cloudfront-us-east-1.images.arcpublishing.com" },
      { protocol: "https", hostname: "files.lanacion.com.py" },
      { protocol: "https", hostname: "i.ytimg.com" },
      { protocol: "https", hostname: "img.youtube.com" },
      { protocol: "https", hostname: "www.popular.com.py" },
      { protocol: "http", hostname: "www.popular.com.py" },
      { protocol: "https", hostname: "popular.com.py" },
      { protocol: "http", hostname: "popular.com.py" },
      { protocol: "https", hostname: "www.adndigital.com.py" },
      { protocol: "http", hostname: "www.adndigital.com.py" },
      { protocol: "https", hostname: "adndigital.com.py" },
      { protocol: "http", hostname: "adndigital.com.py" },
      { protocol: "https", hostname: "noticiascde.com.py" },
      { protocol: "http", hostname: "noticiascde.com.py" },
      { protocol: "https", hostname: "www.noticiascde.com.py" },
      { protocol: "http", hostname: "www.noticiascde.com.py" },
      { protocol: "https", hostname: "1000noticias.com.py" },
      { protocol: "http", hostname: "1000noticias.com.py" },
      { protocol: "https", hostname: "www.1000noticias.com.py" },
      { protocol: "http", hostname: "www.1000noticias.com.py" },
      { protocol: "https", hostname: "ui-avatars.com" },
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "liga-paraguaya-futbol.onrender.com" },
      { protocol: "http", hostname: "liga-paraguaya-futbol.onrender.com" },
    ],
  },
};

export default nextConfig;
