from ..schemas.tactico import (
    AnalisisPartido,
    EquipoPartidoTactico,
    EquipoTactico,
    EstadisticasEquipo,
    InsightTactico,
    JugadorTactico,
    PartidoResumen,
    PrediccionIA,
    StatsComparativa,
)


# Datos mock realistas para los 12 clubes de la liga paraguaya
EQUIPOS_MOCK = {
    "cerro": {
        "nombre": "Cerro PorteÃ±o",
        "escudo": "/cerro-porteno-logo-footylogos.png",
        "formacion_principal": "4-3-3",
        "formaciones_disponibles": ["4-3-3", "4-4-2", "3-5-2"],
        "jugadores": [
            JugadorTactico(id="cerro_1", nombre="Anthony Silva", posicion="POR", numero=1, rating=7.2, x=0.5, y=0.95),
            JugadorTactico(id="cerro_2", nombre="Jorge Moreira", posicion="LD", numero=2, rating=7.0, x=0.85, y=0.75),
            JugadorTactico(id="cerro_3", nombre="Juan PatiÃ±o", posicion="DFC", numero=3, rating=7.3, x=0.65, y=0.8),
            JugadorTactico(id="cerro_4", nombre="CÃ©sar BenÃ­tez", posicion="DFC", numero=4, rating=7.1, x=0.35, y=0.8),
            JugadorTactico(id="cerro_5", nombre="Ayrton Cougo", posicion="LI", numero=6, rating=6.9, x=0.15, y=0.75),
            JugadorTactico(id="cerro_6", nombre="Francisco da Costa", posicion="MCD", numero=5, rating=7.4, x=0.5, y=0.6),
            JugadorTactico(id="cerro_7", nombre="Ricardo Mazacote", posicion="MC", numero=8, rating=7.2, x=0.65, y=0.5),
            JugadorTactico(id="cerro_8", nombre="Lucas Barrios", posicion="MC", numero=10, rating=7.8, x=0.35, y=0.5),
            JugadorTactico(id="cerro_9", nombre="Robert Morales", posicion="ED", numero=7, rating=7.5, x=0.85, y=0.35),
            JugadorTactico(id="cerro_10", nombre="Juan Lucero", posicion="DC", numero=9, rating=7.9, x=0.5, y=0.25),
            JugadorTactico(id="cerro_11", nombre="Braian Samudio", posicion="EI", numero=11, rating=7.3, x=0.15, y=0.35),
        ],
        "stats": EstadisticasEquipo(xg=1.85, posesion=54.2, tiros_puerta=5.2, pases_completados=82.1, duelos_ganados=58.4, corners=6.1),
        "tendencias": [
            InsightTactico(icono="âš½", texto="Marca el 68% de sus goles en el segundo tiempo", metrica="68%"),
            InsightTactico(icono="ðŸ”¥", texto="Invicto en 8 partidos como local", metrica="8 partidos"),
            InsightTactico(icono="ðŸ“Š", texto="Mejor pressing alto de la liga: recupera en 4.2s", metrica="4.2s"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-07-10", rival="Olimpia", resultado="2-1", formacion="4-3-3"),
            PartidoResumen(fecha="2026-07-05", rival="Libertad", resultado="1-0", formacion="4-3-3"),
            PartidoResumen(fecha="2026-06-28", rival="GuaranÃ­", resultado="3-2", formacion="4-4-2"),
        ],
    },
    "olimpi": {
        "nombre": "Olimpia",
        "escudo": "/olimpia-logo-footylogos.png",
        "formacion_principal": "4-4-2",
        "formaciones_disponibles": ["4-4-2", "4-3-3", "3-4-3"],
        "jugadores": [
            JugadorTactico(id="olimpi_1", nombre="GastÃ³n Guruceaga", posicion="POR", numero=1, rating=7.0, x=0.5, y=0.95),
            JugadorTactico(id="olimpi_2", nombre="Fernando Amorebieta", posicion="LD", numero=2, rating=7.1, x=0.85, y=0.75),
            JugadorTactico(id="olimpi_3", nombre="David Mendieta", posicion="DFC", numero=3, rating=7.2, x=0.65, y=0.8),
            JugadorTactico(id="olimpi_4", nombre="Julio CÃ©sar Casserres", posicion="DFC", numero=4, rating=7.0, x=0.35, y=0.8),
            JugadorTactico(id="olimpi_5", nombre="Blas Riveros", posicion="LI", numero=6, rating=7.3, x=0.15, y=0.75),
            JugadorTactico(id="olimpi_6", nombre="Marcos Gamarra", posicion="MC", numero=5, rating=7.1, x=0.7, y=0.55),
            JugadorTactico(id="olimpi_7", nombre="Jorge Recalde", posicion="MD", numero=8, rating=7.0, x=0.5, y=0.6),
            JugadorTactico(id="olimpi_8", nombre="Derlis GonzÃ¡lez", posicion="MI", numero=10, rating=7.6, x=0.3, y=0.55),
            JugadorTactico(id="olimpi_9", nombre="Rodrigo Amaral", posicion="MD", numero=7, rating=7.4, x=0.85, y=0.4),
            JugadorTactico(id="olimpi_10", nombre="Bruno Valdez", posicion="DC", numero=9, rating=7.7, x=0.55, y=0.25),
            JugadorTactico(id="olimpi_11", nombre="William Mendieta", posicion="MI", numero=11, rating=7.2, x=0.15, y=0.4),
        ],
        "stats": EstadisticasEquipo(xg=1.62, posesion=51.8, tiros_puerta=4.8, pases_completados=79.5, duelos_ganados=55.2, corners=5.4),
        "tendencias": [
            InsightTactico(icono="ðŸ“ˆ", texto="Marca el 62% de sus goles en el primer tiempo", metrica="62%"),
            InsightTactico(icono="ðŸŸï¸", texto="No pierde en 5 visitas consecutivas", metrica="5 partidos"),
            InsightTactico(icono="ðŸŽ¯", texto="Promedia 2.1 goles por partido en Ãºltimos 10", metrica="2.1 goles"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-07-10", rival="Cerro", resultado="1-2", formacion="4-4-2"),
            PartidoResumen(fecha="2026-07-03", rival="Nacional", resultado="3-0", formacion="4-4-2"),
            PartidoResumen(fecha="2026-06-29", rival="Cerro", resultado="0-0", formacion="4-3-3"),
        ],
    },
    "libert": {
        "nombre": "Libertad",
        "escudo": "/club-libertad-logo-footylogos.png",
        "formacion_principal": "4-2-3-1",
        "formaciones_disponibles": ["4-2-3-1", "4-3-3", "4-4-1-1"],
        "jugadores": [
            JugadorTactico(id="libert_1", nombre="MartÃ­n Silva", posicion="POR", numero=1, rating=7.3, x=0.5, y=0.95),
            JugadorTactico(id="libert_2", nombre="IvÃ¡n Piris", posicion="LD", numero=2, rating=7.0, x=0.85, y=0.75),
            JugadorTactico(id="libert_3", nombre="Paulo da Silva", posicion="DFC", numero=3, rating=7.5, x=0.65, y=0.8),
            JugadorTactico(id="libert_4", nombre="Diego Viera", posicion="DFC", numero=4, rating=7.2, x=0.35, y=0.8),
            JugadorTactico(id="libert_5", nombre="Santiago Arzamendia", posicion="LI", numero=6, rating=7.1, x=0.15, y=0.75),
            JugadorTactico(id="libert_6", nombre="Lucas Sanabria", posicion="MCD", numero=5, rating=7.0, x=0.5, y=0.6),
            JugadorTactico(id="libert_7", nombre="MatÃ­as Espinoza", posicion="MCD", numero=8, rating=7.1, x=0.5, y=0.55),
            JugadorTactico(id="libert_8", nombre="Ã“scar Ruiz", posicion="MCO", numero=10, rating=7.6, x=0.5, y=0.4),
            JugadorTactico(id="libert_9", nombre="NÃ©stor Camacho", posicion="MD", numero=7, rating=7.3, x=0.85, y=0.35),
            JugadorTactico(id="libert_10", nombre="Luis Amarilla", posicion="DC", numero=9, rating=7.8, x=0.5, y=0.2),
            JugadorTactico(id="libert_11", nombre="Ã“scar Caceres", posicion="MI", numero=11, rating=7.2, x=0.15, y=0.35),
        ],
        "stats": EstadisticasEquipo(xg=1.92, posesion=56.3, tiros_puerta=5.8, pases_completados=84.2, duelos_ganados=60.1, corners=6.8),
        "tendencias": [
            InsightTactico(icono="ðŸ†", texto="LÃ­der de la tabla con 35 puntos", metrica="1ro"),
            InsightTactico(icono="ðŸ”¥", texto="12 victorias en 15 partidos (80%)", metrica="80%"),
            InsightTactico(icono="âš½", texto="Mejor ataque: 2.4 goles por partido", metrica="2.4 goles"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-07-09", rival="GuaranÃ­", resultado="2-0", formacion="4-2-3-1"),
            PartidoResumen(fecha="2026-07-05", rival="Cerro", resultado="0-1", formacion="4-2-3-1"),
            PartidoResumen(fecha="2026-06-30", rival="Sportivo LuqueÃ±o", resultado="3-1", formacion="4-3-3"),
        ],
    },
    "guaran": {
        "nombre": "GuaranÃ­",
        "escudo": "/guarani-paraguay-logo-footylogos.png",
        "formacion_principal": "4-3-3",
        "formaciones_disponibles": ["4-3-3", "4-4-2"],
        "jugadores": [
            JugadorTactico(id="guaran_1", nombre="Pedro FernÃ¡ndez", posicion="POR", numero=1, rating=7.1, x=0.5, y=0.95),
            JugadorTactico(id="guaran_2", nombre="Marcelo Torales", posicion="LD", numero=2, rating=6.9, x=0.85, y=0.75),
            JugadorTactico(id="guaran_3", nombre="Enzo GimÃ©nez", posicion="DFC", numero=3, rating=7.0, x=0.65, y=0.8),
            JugadorTactico(id="guaran_4", nombre="Luis FariÃ±a", posicion="DFC", numero=4, rating=6.8, x=0.35, y=0.8),
            JugadorTactico(id="guaran_5", nombre="Alfredo Aguilar", posicion="LI", numero=6, rating=7.0, x=0.15, y=0.75),
            JugadorTactico(id="guaran_6", nombre="Jorge Mendoza", posicion="MC", numero=5, rating=7.2, x=0.5, y=0.6),
            JugadorTactico(id="guaran_7", nombre="Richard Prieto", posicion="MC", numero=8, rating=7.1, x=0.65, y=0.55),
            JugadorTactico(id="guaran_8", nombre="Fernando FernÃ¡ndez", posicion="MC", numero=10, rating=7.4, x=0.35, y=0.55),
            JugadorTactico(id="guaran_9", nombre="Thomas Gamarra", posicion="ED", numero=7, rating=7.2, x=0.85, y=0.35),
            JugadorTactico(id="guaran_10", nombre="Cecilio DomÃ­nguez", posicion="DC", numero=9, rating=7.6, x=0.5, y=0.25),
            JugadorTactico(id="guaran_11", nombre="Rodrigo Fleitas", posicion="EI", numero=11, rating=7.0, x=0.15, y=0.35),
        ],
        "stats": EstadisticasEquipo(xg=1.45, posesion=48.5, tiros_puerta=4.2, pases_completados=76.8, duelos_ganados=52.3, corners=4.9),
        "tendencias": [
            InsightTactico(icono="ðŸ’ª", texto="Gana el 70% de duelos aÃ©reos", metrica="70%"),
            InsightTactico(icono="ðŸŽ¯", texto="Cecilio DomÃ­nguez: goleador con 8 tantos", metrica="8 goles"),
            InsightTactico(icono="ðŸ“Š", texto="Promedia 4.2 tiros a puerta por partido", metrica="4.2 tiros"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-07-09", rival="Libertad", resultado="0-2", formacion="4-3-3"),
            PartidoResumen(fecha="2026-07-02", rival="Nacional", resultado="2-1", formacion="4-3-3"),
            PartidoResumen(fecha="2026-06-28", rival="Cerro", resultado="2-3", formacion="4-4-2"),
        ],
    },
    "nacion": {
        "nombre": "Nacional",
        "escudo": "/nacional-paraguay-logo-footylogos.png",
        "formacion_principal": "4-4-2",
        "formaciones_disponibles": ["4-4-2", "4-3-3", "5-3-2"],
        "jugadores": [
            JugadorTactico(id="nacion_1", nombre="Rodrigo MuÃ±oz", posicion="POR", numero=1, rating=7.4, x=0.5, y=0.95),
            JugadorTactico(id="nacion_2", nombre="Carlos Bonet", posicion="LD", numero=2, rating=7.0, x=0.85, y=0.75),
            JugadorTactico(id="nacion_3", nombre="Alberto Contreras", posicion="DFC", numero=3, rating=7.2, x=0.65, y=0.8),
            JugadorTactico(id="nacion_4", nombre="Marcelo Peralta", posicion="DFC", numero=4, rating=7.1, x=0.35, y=0.8),
            JugadorTactico(id="nacion_5", nombre="Fernando BenÃ­tez", posicion="LI", numero=6, rating=6.9, x=0.15, y=0.75),
            JugadorTactico(id="nacion_6", nombre="Hugo FernÃ¡ndez", posicion="MC", numero=5, rating=7.3, x=0.7, y=0.55),
            JugadorTactico(id="nacion_7", nombre="Guido Vinti", posicion="MC", numero=8, rating=7.0, x=0.3, y=0.55),
            JugadorTactico(id="nacion_8", nombre="Alejandro Paiva", posicion="MD", numero=7, rating=7.2, x=0.85, y=0.4),
            JugadorTactico(id="nacion_9", nombre="Julio IrrazÃ¡bal", posicion="MI", numero=11, rating=7.1, x=0.15, y=0.4),
            JugadorTactico(id="nacion_10", nombre="TomÃ¡s Caceres", posicion="DC", numero=9, rating=7.5, x=0.55, y=0.25),
            JugadorTactico(id="nacion_11", nombre="AdriÃ¡n MartÃ­nez", posicion="DC", numero=10, rating=7.3, x=0.45, y=0.25),
        ],
        "stats": EstadisticasEquipo(xg=1.38, posesion=47.2, tiros_puerta=4.0, pases_completados=75.3, duelos_ganados=54.8, corners=4.5),
        "tendencias": [
            InsightTactico(icono="ðŸ›¡ï¸", texto="Defensa sÃ³lida: solo 0.8 goles recibidos por partido", metrica="0.8 goles"),
            InsightTactico(icono="âš¡", texto="Contragolpe letal: 45% de sus goles son de contra", metrica="45%"),
            InsightTactico(icono="ðŸŸï¸", texto="Invicto en 4 partidos en el Arsenio Erico", metrica="4 partidos"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-07-03", rival="Olimpia", resultado="0-3", formacion="4-4-2"),
            PartidoResumen(fecha="2026-07-02", rival="GuaranÃ­", resultado="1-2", formacion="4-4-2"),
            PartidoResumen(fecha="2026-06-25", rival="Sportivo LuqueÃ±o", resultado="1-0", formacion="5-3-2"),
        ],
    },
    "spoluq": {
        "nombre": "Sportivo LuqueÃ±o",
        "escudo": "/sportivo-luqueno-logo-footylogos.png",
        "formacion_principal": "4-3-3",
        "formaciones_disponibles": ["4-3-3", "4-4-2"],
        "jugadores": [
            JugadorTactico(id="spoluq_1", nombre="Diego Barreto", posicion="POR", numero=1, rating=6.9, x=0.5, y=0.95),
            JugadorTactico(id="spoluq_2", nombre="HÃ©ctor Villalba", posicion="LD", numero=2, rating=7.0, x=0.85, y=0.75),
            JugadorTactico(id="spoluq_3", nombre="Pedro Sarabia", posicion="DFC", numero=3, rating=7.1, x=0.65, y=0.8),
            JugadorTactico(id="spoluq_4", nombre="Walter Bogado", posicion="DFC", numero=4, rating=6.8, x=0.35, y=0.8),
            JugadorTactico(id="spoluq_5", nombre="FabiÃ¡n Caballero", posicion="LI", numero=6, rating=6.7, x=0.15, y=0.75),
            JugadorTactico(id="spoluq_6", nombre="Osvaldo Hinzpeter", posicion="MC", numero=5, rating=7.0, x=0.5, y=0.6),
            JugadorTactico(id="spoluq_7", nombre="MatÃ­as Vera", posicion="MC", numero=8, rating=7.2, x=0.65, y=0.55),
            JugadorTactico(id="spoluq_8", nombre="David Mendoza", posicion="MC", numero=10, rating=7.3, x=0.35, y=0.55),
            JugadorTactico(id="spoluq_9", nombre="Basilio FlorentÃ­n", posicion="ED", numero=7, rating=7.1, x=0.85, y=0.35),
            JugadorTactico(id="spoluq_10", nombre="Nelson Haedo Parra", posicion="DC", numero=9, rating=7.4, x=0.5, y=0.25),
            JugadorTactico(id="spoluq_11", nombre="Luis Ovelar", posicion="EI", numero=11, rating=6.9, x=0.15, y=0.35),
        ],
        "stats": EstadisticasEquipo(xg=1.32, posesion=46.8, tiros_puerta=3.9, pases_completados=74.2, duelos_ganados=51.5, corners=4.2),
        "tendencias": [
            InsightTactico(icono="ðŸ“ˆ", texto="MejorÃ­a notable: 4 victorias en Ãºltimos 6", metrica="4 victorias"),
            InsightTactico(icono="ðŸŽ¯", texto="Nelson Haedo Parra: 6 goles en temporada", metrica="6 goles"),
            InsightTactico(icono="ðŸŸï¸", texto="RÃ©cord de asistencia: 12,000 vs Olimpia", metrica="12k"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-07-06", rival="General DÃ­az", resultado="2-0", formacion="4-3-3"),
            PartidoResumen(fecha="2026-06-30", rival="Libertad", resultado="1-3", formacion="4-3-3"),
            PartidoResumen(fecha="2026-06-25", rival="Nacional", resultado="0-1", formacion="4-4-2"),
        ],
    },
    "gendi": {
        "nombre": "General DÃ­az",
        "escudo": "https://upload.wikimedia.org/wikipedia/en/2/2a/Club_General_D%C3%ADaz.png",
        "formacion_principal": "5-3-2",
        "formaciones_disponibles": ["5-3-2", "4-4-2", "3-5-2"],
        "jugadores": [
            JugadorTactico(id="gendi_1", nombre="Alfredo Aguilar", posicion="POR", numero=1, rating=7.0, x=0.5, y=0.95),
            JugadorTactico(id="gendi_2", nombre="Juan Aguilar", posicion="DFD", numero=2, rating=6.8, x=0.9, y=0.75),
            JugadorTactico(id="gendi_3", nombre="Marcos Caceres", posicion="DFC", numero=3, rating=7.1, x=0.7, y=0.8),
            JugadorTactico(id="gendi_4", nombre="Paulo Carvallo", posicion="DFC", numero=4, rating=7.0, x=0.5, y=0.82),
            JugadorTactico(id="gendi_5", nombre="Julio Baez", posicion="DFC", numero=5, rating=6.9, x=0.3, y=0.8),
            JugadorTactico(id="gendi_6", nombre="Sergio Aquino", posicion="DFI", numero=6, rating=6.7, x=0.1, y=0.75),
            JugadorTactico(id="gendi_7", nombre="Mauro Bogado", posicion="MC", numero=7, rating=7.0, x=0.65, y=0.55),
            JugadorTactico(id="gendi_8", nombre="Jorge GonzÃ¡lez", posicion="MC", numero=8, rating=6.9, x=0.5, y=0.6),
            JugadorTactico(id="gendi_9", nombre="Cristian Sosa", posicion="MC", numero=10, rating=7.1, x=0.35, y=0.55),
            JugadorTactico(id="gendi_10", nombre="Franco Vera", posicion="DC", numero=9, rating=7.3, x=0.55, y=0.25),
            JugadorTactico(id="gendi_11", nombre="Arnaldo Castillo", posicion="DC", numero=11, rating=7.2, x=0.45, y=0.25),
        ],
        "stats": EstadisticasEquipo(xg=1.15, posesion=44.5, tiros_puerta=3.5, pases_completados=72.8, duelos_ganados=53.2, corners=3.8),
        "tendencias": [
            InsightTactico(icono="ðŸ›¡ï¸", texto="Defensa impenetrable: 0.6 goles recibidos por partido", metrica="0.6 goles"),
            InsightTactico(icono="âš”ï¸", texto="Duo letal: Franco Vera y Arnoldo Castillo suman 12 goles", metrica="12 goles"),
            InsightTactico(icono="ðŸ“Š", texto="Promedia 5.2 duelos ganados por jugador", metrica="5.2"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-07-06", rival="Sportivo LuqueÃ±o", resultado="0-2", formacion="5-3-2"),
            PartidoResumen(fecha="2026-06-29", rival="Deportivo CapiatÃ¡", resultado="1-1", formacion="5-3-2"),
            PartidoResumen(fecha="2026-06-22", rival="Sol de AmÃ©rica", resultado="2-0", formacion="4-4-2"),
        ],
    },
    "depcai": {
        "nombre": "Deportivo CapiatÃ¡",
        "escudo": "/clubdeportivo_capiata.png",
        "formacion_principal": "4-4-2",
        "formaciones_disponibles": ["4-4-2", "4-3-3"],
        "jugadores": [
            JugadorTactico(id="depcai_1", nombre="Carlos ServÃ­n", posicion="POR", numero=1, rating=6.8, x=0.5, y=0.95),
            JugadorTactico(id="depcai_2", nombre="Alexis Villalba", posicion="LD", numero=2, rating=6.7, x=0.85, y=0.75),
            JugadorTactico(id="depcai_3", nombre="Oscar BenÃ­tez", posicion="DFC", numero=3, rating=6.9, x=0.65, y=0.8),
            JugadorTactico(id="depcai_4", nombre="Francisco Franco", posicion="DFC", numero=4, rating=6.8, x=0.35, y=0.8),
            JugadorTactico(id="depcai_5", nombre="Jorge Paredes", posicion="LI", numero=6, rating=6.6, x=0.15, y=0.75),
            JugadorTactico(id="depcai_6", nombre="Paulo Santos", posicion="MC", numero=5, rating=6.9, x=0.7, y=0.55),
            JugadorTactico(id="depcai_7", nombre="Luis de la Cruz", posicion="MC", numero=8, rating=6.8, x=0.3, y=0.55),
            JugadorTactico(id="depcai_8", nombre="Fernando Battiste", posicion="MD", numero=7, rating=7.0, x=0.85, y=0.4),
            JugadorTactico(id="depcai_9", nombre="Brian Montenegro", posicion="MI", numero=11, rating=7.1, x=0.15, y=0.4),
            JugadorTactico(id="depcai_10", nombre="Richard Salcedo", posicion="DC", numero=9, rating=7.2, x=0.55, y=0.25),
            JugadorTactico(id="depcai_11", nombre="VÃ­ctor Ãvalos", posicion="DC", numero=10, rating=7.0, x=0.45, y=0.25),
        ],
        "stats": EstadisticasEquipo(xg=1.22, posesion=45.8, tiros_puerta=3.8, pases_completados=73.5, duelos_ganados=50.8, corners=4.0),
        "tendencias": [
            InsightTactico(icono="âš¡", texto="RÃ¡pida transiciÃ³n: promedia 3.2 segundos de contra", metrica="3.2s"),
            InsightTactico(icono="ðŸŽ¯", texto="Richard Salcedo: 5 goles en Ãºltimos 8 partidos", metrica="5 goles"),
            InsightTactico(icono="ðŸ“Š", texto="Mejor porcentaje de duelos aÃ©reos: 62%", metrica="62%"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-06-29", rival="General DÃ­az", resultado="1-1", formacion="4-4-2"),
            PartidoResumen(fecha="2026-06-22", rival="Nacional", resultado="0-2", formacion="4-4-2"),
            PartidoResumen(fecha="2026-06-15", rival="3 de Febrero", resultado="2-1", formacion="4-3-3"),
        ],
    },
    "trifeb": {
        "nombre": "3 de Febrero",
        "escudo": "https://upload.wikimedia.org/wikipedia/en/a/a1/Club_3_Febrero.png",
        "formacion_principal": "4-3-3",
        "formaciones_disponibles": ["4-3-3", "4-4-2", "3-4-3"],
        "jugadores": [
            JugadorTactico(id="trifeb_1", nombre="JosÃ© Caravali", posicion="POR", numero=1, rating=6.7, x=0.5, y=0.95),
            JugadorTactico(id="trifeb_2", nombre="Pedro Riveros", posicion="LD", numero=2, rating=6.6, x=0.85, y=0.75),
            JugadorTactico(id="trifeb_3", nombre="Rodrigo LÃ³pez", posicion="DFC", numero=3, rating=6.8, x=0.65, y=0.8),
            JugadorTactico(id="trifeb_4", nombre="Marcos DurÃ©", posicion="DFC", numero=4, rating=6.7, x=0.35, y=0.8),
            JugadorTactico(id="trifeb_5", nombre="Juan Torales", posicion="LI", numero=6, rating=6.5, x=0.15, y=0.75),
            JugadorTactico(id="trifeb_6", nombre="Carlos GonzÃ¡lez", posicion="MCD", numero=5, rating=6.9, x=0.5, y=0.6),
            JugadorTactico(id="trifeb_7", nombre="HernÃ¡n LÃ³pez", posicion="MC", numero=8, rating=7.0, x=0.65, y=0.55),
            JugadorTactico(id="trifeb_8", nombre="MatÃ­as Barreto", posicion="MC", numero=10, rating=7.1, x=0.35, y=0.55),
            JugadorTactico(id="trifeb_9", nombre="Santiago Salcedo", posicion="ED", numero=7, rating=7.3, x=0.85, y=0.35),
            JugadorTactico(id="trifeb_10", nombre="Enrique Vera", posicion="DC", numero=9, rating=7.0, x=0.5, y=0.25),
            JugadorTactico(id="trifeb_11", nombre="Bautista Merlini", posicion="EI", numero=11, rating=6.8, x=0.15, y=0.35),
        ],
        "stats": EstadisticasEquipo(xg=1.08, posesion=43.2, tiros_puerta=3.2, pases_completados=71.5, duelos_ganados=49.2, corners=3.5),
        "tendencias": [
            InsightTactico(icono="ðŸŒŸ", texto="Santiago Salcedo: Ã­dolo con 150+ goles en su carrera", metrica="150+ goles"),
            InsightTactico(icono="ðŸ“Š", texto="Promedio mÃ¡s bajo de la liga: 1.08 xG", metrica="1.08 xG"),
            InsightTactico(icono="ðŸ’ª", texto="Lucha por la permanencia: 3 victorias en Ãºltimos 10", metrica="3 victorias"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-06-22", rival="Sol de AmÃ©rica", resultado="1-0", formacion="4-3-3"),
            PartidoResumen(fecha="2026-06-15", rival="Deportivo CapiatÃ¡", resultado="1-2", formacion="4-3-3"),
            PartidoResumen(fecha="2026-06-08", rival="Sportivo Ameliano", resultado="0-1", formacion="4-4-2"),
        ],
    },
    "solame": {
        "nombre": "Sol de AmÃ©rica",
        "escudo": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Escudo_de_sol_de_am%C3%A9rica.png",
        "formacion_principal": "4-4-2",
        "formaciones_disponibles": ["4-4-2", "4-3-3", "5-3-2"],
        "jugadores": [
            JugadorTactico(id="solame_1", nombre="Roberto RamÃ­rez", posicion="POR", numero=1, rating=6.6, x=0.5, y=0.95),
            JugadorTactico(id="solame_2", nombre="Dante LÃ³pez", posicion="LD", numero=2, rating=6.5, x=0.85, y=0.75),
            JugadorTactico(id="solame_3", nombre="Manuel Balbuena", posicion="DFC", numero=3, rating=6.7, x=0.65, y=0.8),
            JugadorTactico(id="solame_4", nombre="Eduardo Aranda", posicion="DFC", numero=4, rating=6.6, x=0.35, y=0.8),
            JugadorTactico(id="solame_5", nombre="Marcelo Paredes", posicion="LI", numero=6, rating=6.4, x=0.15, y=0.75),
            JugadorTactico(id="solame_6", nombre="Ãngel Ruiz", posicion="MC", numero=5, rating=6.8, x=0.7, y=0.55),
            JugadorTactico(id="solame_7", nombre="Jorge Scolari", posicion="MC", numero=8, rating=6.7, x=0.3, y=0.55),
            JugadorTactico(id="solame_8", nombre="Lucas Barrios Jr", posicion="MD", numero=7, rating=6.9, x=0.85, y=0.4),
            JugadorTactico(id="solame_9", nombre="Fernando Arias", posicion="MI", numero=11, rating=6.8, x=0.15, y=0.4),
            JugadorTactico(id="solame_10", nombre="Cristian Riveros", posicion="DC", numero=9, rating=7.1, x=0.55, y=0.25),
            JugadorTactico(id="solame_11", nombre="JosÃ© Ortigoza", posicion="DC", numero=10, rating=7.3, x=0.45, y=0.25),
        ],
        "stats": EstadisticasEquipo(xg=1.18, posesion=46.2, tiros_puerta=3.6, pases_completados=74.0, duelos_ganados=51.0, corners=4.1),
        "tendencias": [
            InsightTactico(icono="ðŸŽ¯", texto="JosÃ© Ortigoza: goleador histÃ³rico con 200+ tantos", metrica="200+ goles"),
            InsightTactico(icono="ðŸ“Š", texto="Balanced: ni muy atacante ni muy defensivo", metrica="Balanceado"),
            InsightTactico(icono="ðŸŸï¸", texto="Buena racha en casa: 3 victorias en Ãºltimos 4", metrica="3 victorias"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-06-22", rival="3 de Febrero", resultado="0-1", formacion="4-4-2"),
            PartidoResumen(fecha="2026-06-15", rival="General DÃ­az", resultado="0-2", formacion="4-4-2"),
            PartidoResumen(fecha="2026-06-08", rival="Nacional", resultado="1-1", formacion="4-3-3"),
        ],
    },
    "spamel": {
        "nombre": "Sportivo Ameliano",
        "escudo": "https://upload.wikimedia.org/wikipedia/en/e/e5/Club_Sportivo_Ameliano.png",
        "formacion_principal": "4-3-3",
        "formaciones_disponibles": ["4-3-3", "4-4-2"],
        "jugadores": [
            JugadorTactico(id="spamel_1", nombre="Pedro AcuÃ±a", posicion="POR", numero=1, rating=6.7, x=0.5, y=0.95),
            JugadorTactico(id="spamel_2", nombre="Walter GonzÃ¡lez", posicion="LD", numero=2, rating=6.6, x=0.85, y=0.75),
            JugadorTactico(id="spamel_3", nombre="Rodrigo Amaral", posicion="DFC", numero=3, rating=6.8, x=0.65, y=0.8),
            JugadorTactico(id="spamel_4", nombre="Fernando FernÃ¡ndez Jr", posicion="DFC", numero=4, rating=6.7, x=0.35, y=0.8),
            JugadorTactico(id="spamel_5", nombre="NÃ©stor Camacho Jr", posicion="LI", numero=6, rating=6.5, x=0.15, y=0.75),
            JugadorTactico(id="spamel_6", nombre="Richard Prieto Jr", posicion="MC", numero=5, rating=6.9, x=0.5, y=0.6),
            JugadorTactico(id="spamel_7", nombre="Juan Iturbe", posicion="MC", numero=8, rating=7.2, x=0.65, y=0.55),
            JugadorTactico(id="spamel_8", nombre="FabiÃ¡n Espinoza", posicion="MC", numero=10, rating=7.0, x=0.35, y=0.55),
            JugadorTactico(id="spamel_9", nombre="Alexis DomÃ­nguez", posicion="ED", numero=7, rating=6.8, x=0.85, y=0.35),
            JugadorTactico(id="spamel_10", nombre="Brian GimÃ©nez", posicion="DC", numero=9, rating=7.1, x=0.5, y=0.25),
            JugadorTactico(id="spamel_11", nombre="Cecilio DomÃ­nguez Jr", posicion="EI", numero=11, rating=6.9, x=0.15, y=0.35),
        ],
        "stats": EstadisticasEquipo(xg=1.25, posesion=47.5, tiros_puerta=4.0, pases_completados=75.2, duelos_ganados=52.8, corners=4.3),
        "tendencias": [
            InsightTactico(icono="ðŸŒŸ", texto="Juan Iturbe: ex-Paraguay con calidad sudamericana", metrica="7.2 rating"),
            InsightTactico(icono="âš¡", texto="Juego ofensivo: promedia 4.0 tiros a puerta", metrica="4.0 tiros"),
            InsightTactico(icono="ðŸ“Š", texto="Mejor porcentaje de posesiÃ³n vs rivales directos", metrica="48.5%"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-06-08", rival="3 de Febrero", resultado="1-0", formacion="4-3-3"),
            PartidoResumen(fecha="2026-06-01", rival="GuaranÃ­", resultado="1-2", formacion="4-3-3"),
            PartidoResumen(fecha="2026-05-25", rival="Deportivo CapiatÃ¡", resultado="0-0", formacion="4-4-2"),
        ],
    },
    "coleg": {
        "nombre": "Colegiales",
        "escudo": "https://upload.wikimedia.org/wikipedia/commons/6/63/Club_atletico_colegiales.png",
        "formacion_principal": "4-4-2",
        "formaciones_disponibles": ["4-4-2", "4-3-3"],
        "jugadores": [
            JugadorTactico(id="coleg_1", nombre="Miguel MartÃ­nez", posicion="POR", numero=1, rating=6.5, x=0.5, y=0.95),
            JugadorTactico(id="coleg_2", nombre="RaÃºl Torres", posicion="LD", numero=2, rating=6.4, x=0.85, y=0.75),
            JugadorTactico(id="coleg_3", nombre="Fabio Ramos", posicion="DFC", numero=3, rating=6.6, x=0.65, y=0.8),
            JugadorTactico(id="coleg_4", nombre="Carlos BenÃ­tez", posicion="DFC", numero=4, rating=6.5, x=0.35, y=0.8),
            JugadorTactico(id="coleg_5", nombre="Pedro LÃ³pez", posicion="LI", numero=6, rating=6.3, x=0.15, y=0.75),
            JugadorTactico(id="coleg_6", nombre="Ã“scar Gamarra", posicion="MC", numero=5, rating=6.7, x=0.7, y=0.55),
            JugadorTactico(id="coleg_7", nombre="Juan Espinoza", posicion="MC", numero=8, rating=6.6, x=0.3, y=0.55),
            JugadorTactico(id="coleg_8", nombre="Santiago Amarilla", posicion="MD", numero=7, rating=6.5, x=0.85, y=0.4),
            JugadorTactico(id="coleg_9", nombre="Diego Valdez", posicion="MI", numero=11, rating=6.4, x=0.15, y=0.4),
            JugadorTactico(id="coleg_10", nombre="Lucas FernÃ¡ndez", posicion="DC", numero=9, rating=6.8, x=0.55, y=0.25),
            JugadorTactico(id="coleg_11", nombre="MatÃ­as Olmedo", posicion="DC", numero=10, rating=6.7, x=0.45, y=0.25),
        ],
        "stats": EstadisticasEquipo(xg=1.05, posesion=42.8, tiros_puerta=3.1, pases_completados=70.5, duelos_ganados=48.7, corners=3.2),
        "tendencias": [
            InsightTactico(icono="ðŸ›¡ï¸", texto="Juego defensivo: promedia 0.9 goles recibidos por partido", metrica="0.9 goles"),
            InsightTactico(icono="ðŸ“Š", texto="Menor posesiÃ³n de la liga: 42.8%", metrica="42.8%"),
            InsightTactico(icono="âš¡", texto="Contraataque efectivo: 35% de sus goles son de contra", metrica="35%"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-06-22", rival="Nacional", resultado="0-1", formacion="4-4-2"),
            PartidoResumen(fecha="2026-06-15", rival="GuaranÃ­", resultado="1-2", formacion="4-4-2"),
            PartidoResumen(fecha="2026-06-08", rival="Libertad", resultado="0-0", formacion="4-3-3"),
        ],
    },
    "gcab": {
        "nombre": "General Caballero (JLM)",
        "escudo": "/general-caballero-jlm-logo-footylogos.png",
        "formacion_principal": "4-3-3",
        "formaciones_disponibles": ["4-3-3", "4-4-2"],
        "jugadores": [
            JugadorTactico(id="gcab_1", nombre="Alfredo MartÃ­nez", posicion="POR", numero=1, rating=6.4, x=0.5, y=0.95),
            JugadorTactico(id="gcab_2", nombre="Roberto Rojas", posicion="LD", numero=2, rating=6.3, x=0.85, y=0.75),
            JugadorTactico(id="gcab_3", nombre="Marcos Aquino", posicion="DFC", numero=3, rating=6.5, x=0.65, y=0.8),
            JugadorTactico(id="gcab_4", nombre="VÃ­ctor Medina", posicion="DFC", numero=4, rating=6.4, x=0.35, y=0.8),
            JugadorTactico(id="gcab_5", nombre="Eduardo Fleitas", posicion="LI", numero=6, rating=6.2, x=0.15, y=0.75),
            JugadorTactico(id="gcab_6", nombre="Hugo BenÃ­tez", posicion="MC", numero=5, rating=6.6, x=0.65, y=0.55),
            JugadorTactico(id="gcab_7", nombre="RaÃºl Oviedo", posicion="MC", numero=8, rating=6.5, x=0.5, y=0.6),
            JugadorTactico(id="gcab_8", nombre="Diego Lezcano", posicion="MC", numero=10, rating=6.7, x=0.35, y=0.55),
            JugadorTactico(id="gcab_9", nombre="Brian Peralta", posicion="ED", numero=7, rating=6.5, x=0.85, y=0.35),
            JugadorTactico(id="gcab_10", nombre="Nelson Candia", posicion="DC", numero=9, rating=6.8, x=0.5, y=0.25),
            JugadorTactico(id="gcab_11", nombre="Sergio RamÃ­rez", posicion="EI", numero=11, rating=6.4, x=0.15, y=0.35),
        ],
        "stats": EstadisticasEquipo(xg=1.10, posesion=44.0, tiros_puerta=3.3, pases_completados=71.2, duelos_ganados=50.1, corners=3.5),
        "tendencias": [
            InsightTactico(icono="ðŸ’ª", texto="Nelson Candia: 7 goles en temporada, referente ofensivo", metrica="7 goles"),
            InsightTactico(icono="ðŸ›¡ï¸", texto="Defensa ordenada: solo 1.1 goles recibidos por partido", metrica="1.1 goles"),
            InsightTactico(icono="ðŸ“Š", texto="Equipo balanceado entre ataque y defensa", metrica="Balanceado"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-06-29", rival="Sportivo LuqueÃ±o", resultado="1-1", formacion="4-3-3"),
            PartidoResumen(fecha="2026-06-22", rival="Sol de AmÃ©rica", resultado="2-0", formacion="4-3-3"),
            PartidoResumen(fecha="2026-06-15", rival="General DÃ­az", resultado="0-1", formacion="4-4-2"),
        ],
    },
    "rubio": {
        "nombre": "Rubio Ã‘u",
        "escudo": "https://upload.wikimedia.org/wikipedia/en/7/76/Club_Rubio_%C3%91u_logo.png",
        "formacion_principal": "4-4-2",
        "formaciones_disponibles": ["4-4-2", "3-5-2"],
        "jugadores": [
            JugadorTactico(id="rubio_1", nombre="Joel Romero", posicion="POR", numero=1, rating=6.5, x=0.5, y=0.95),
            JugadorTactico(id="rubio_2", nombre="Marcos GonzÃ¡lez", posicion="LD", numero=2, rating=6.4, x=0.85, y=0.75),
            JugadorTactico(id="rubio_3", nombre="Pedro Delgado", posicion="DFC", numero=3, rating=6.6, x=0.65, y=0.8),
            JugadorTactico(id="rubio_4", nombre="Ãngel Vera", posicion="DFC", numero=4, rating=6.5, x=0.35, y=0.8),
            JugadorTactico(id="rubio_5", nombre="Sergio Achucarro", posicion="LI", numero=6, rating=6.3, x=0.15, y=0.75),
            JugadorTactico(id="rubio_6", nombre="Jorge Recalde", posicion="MD", numero=7, rating=6.6, x=0.85, y=0.5),
            JugadorTactico(id="rubio_7", nombre="RaÃºl OrtÃ­z", posicion="MC", numero=5, rating=6.7, x=0.65, y=0.55),
            JugadorTactico(id="rubio_8", nombre="CÃ©sar Benegas", posicion="MC", numero=8, rating=6.6, x=0.35, y=0.55),
            JugadorTactico(id="rubio_9", nombre="Fernando Ãlvarez", posicion="MI", numero=11, rating=6.5, x=0.15, y=0.5),
            JugadorTactico(id="rubio_10", nombre="Bautista Giordano", posicion="DC", numero=9, rating=6.8, x=0.55, y=0.25),
            JugadorTactico(id="rubio_11", nombre="Lucas Riveros", posicion="DC", numero=10, rating=6.7, x=0.45, y=0.25),
        ],
        "stats": EstadisticasEquipo(xg=1.12, posesion=43.5, tiros_puerta=3.4, pases_completados=71.0, duelos_ganados=49.5, corners=3.6),
        "tendencias": [
            InsightTactico(icono="âš½", texto="Bautista Giordano: goleador del equipo con 6 tantos", metrica="6 goles"),
            InsightTactico(icono="ðŸŸï¸", texto="Buen rendimiento en casa: 4 victorias en Ãºltimos 6", metrica="4 victorias"),
            InsightTactico(icono="ðŸ“Š", texto="Duo ofensivo efectivo: Giordano y Riveros suman 11 goles", metrica="11 goles"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-07-06", rival="Nacional", resultado="1-0", formacion="4-4-2"),
            PartidoResumen(fecha="2026-06-29", rival="Sportivo Trinidense", resultado="2-2", formacion="4-4-2"),
            PartidoResumen(fecha="2026-06-22", rival="Recoleta", resultado="0-1", formacion="3-5-2"),
        ],
    },
    "2mayo": {
        "nombre": "Sportivo 2 de Mayo",
        "escudo": "/club-sportivo-2-de-mayo-logo-footylogos.png",
        "formacion_principal": "4-3-3",
        "formaciones_disponibles": ["4-3-3", "4-4-2"],
        "jugadores": [
            JugadorTactico(id="2mayo_1", nombre="Roberto PÃ©rez", posicion="POR", numero=1, rating=6.6, x=0.5, y=0.95),
            JugadorTactico(id="2mayo_2", nombre="Marcos Aquino", posicion="LD", numero=2, rating=6.5, x=0.85, y=0.75),
            JugadorTactico(id="2mayo_3", nombre="Juan Paniagua", posicion="DFC", numero=3, rating=6.7, x=0.65, y=0.8),
            JugadorTactico(id="2mayo_4", nombre="Fernando Ruiz", posicion="DFC", numero=4, rating=6.6, x=0.35, y=0.8),
            JugadorTactico(id="2mayo_5", nombre="Eduardo Galeano", posicion="LI", numero=6, rating=6.4, x=0.15, y=0.75),
            JugadorTactico(id="2mayo_6", nombre="Santiago Torres", posicion="MC", numero=5, rating=6.8, x=0.65, y=0.55),
            JugadorTactico(id="2mayo_7", nombre="Diego Acosta", posicion="MC", numero=8, rating=6.7, x=0.5, y=0.6),
            JugadorTactico(id="2mayo_8", nombre="RaÃºl Romero", posicion="MC", numero=10, rating=6.9, x=0.35, y=0.55),
            JugadorTactico(id="2mayo_9", nombre="Brian BenÃ­tez", posicion="ED", numero=7, rating=6.7, x=0.85, y=0.35),
            JugadorTactico(id="2mayo_10", nombre="Nelson Segovia", posicion="DC", numero=9, rating=7.0, x=0.5, y=0.25),
            JugadorTactico(id="2mayo_11", nombre="Arnaldo VelÃ¡zquez", posicion="EI", numero=11, rating=6.6, x=0.15, y=0.35),
        ],
        "stats": EstadisticasEquipo(xg=1.28, posesion=46.5, tiros_puerta=3.9, pases_completados=74.8, duelos_ganados=52.0, corners=4.3),
        "tendencias": [
            InsightTactico(icono="âš¡", texto="Nelson Segovia: 9 goles, mÃ¡ximo goleador del equipo", metrica="9 goles"),
            InsightTactico(icono="ðŸŸï¸", texto="RÃ©cord de asistencia: 20,000 en clÃ¡sico del norte", metrica="20k"),
            InsightTactico(icono="ðŸ“Š", texto="Buena defensa: solo 0.9 goles recibidos por partido", metrica="0.9 goles"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-07-10", rival="GuaranÃ­", resultado="2-1", formacion="4-3-3"),
            PartidoResumen(fecha="2026-07-03", rival="Olimpia", resultado="0-0", formacion="4-3-3"),
            PartidoResumen(fecha="2026-06-28", rival="Libertad", resultado="1-2", formacion="4-4-2"),
        ],
    },
    "sanlor": {
        "nombre": "Sportivo San Lorenzo",
        "escudo": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Escudo_Sportivo_San_Lorenzo.png",
        "formacion_principal": "4-4-2",
        "formaciones_disponibles": ["4-4-2", "5-3-2"],
        "jugadores": [
            JugadorTactico(id="sanlor_1", nombre="Carlos ArÃ©valos", posicion="POR", numero=1, rating=6.3, x=0.5, y=0.95),
            JugadorTactico(id="sanlor_2", nombre="Roberto Cabrera", posicion="LD", numero=2, rating=6.2, x=0.85, y=0.75),
            JugadorTactico(id="sanlor_3", nombre="JosÃ© Ortigoza", posicion="DFC", numero=3, rating=6.4, x=0.65, y=0.8),
            JugadorTactico(id="sanlor_4", nombre="Francisco Barrios", posicion="DFC", numero=4, rating=6.3, x=0.35, y=0.8),
            JugadorTactico(id="sanlor_5", nombre="RaÃºl ServÃ­n", posicion="LI", numero=6, rating=6.1, x=0.15, y=0.75),
            JugadorTactico(id="sanlor_6", nombre="Diego MartÃ­nez", posicion="MC", numero=5, rating=6.5, x=0.7, y=0.55),
            JugadorTactico(id="sanlor_7", nombre="Ãngel GonzÃ¡lez", posicion="MC", numero=8, rating=6.4, x=0.3, y=0.55),
            JugadorTactico(id="sanlor_8", nombre="Sergio FernÃ¡ndez", posicion="MD", numero=7, rating=6.3, x=0.85, y=0.4),
            JugadorTactico(id="sanlor_9", nombre="Pedro Amarilla", posicion="MI", numero=11, rating=6.2, x=0.15, y=0.4),
            JugadorTactico(id="sanlor_10", nombre="Lucas QuiÃ±Ã³nez", posicion="DC", numero=9, rating=6.6, x=0.55, y=0.25),
            JugadorTactico(id="sanlor_11", nombre="Nelson Peralta", posicion="DC", numero=10, rating=6.5, x=0.45, y=0.25),
        ],
        "stats": EstadisticasEquipo(xg=0.95, posesion=41.2, tiros_puerta=2.8, pases_completados=68.5, duelos_ganados=47.3, corners=2.9),
        "tendencias": [
            InsightTactico(icono="ðŸ“‰", texto="Ãšltimo en la tabla: 15 puntos en 22 partidos", metrica="16to"),
            InsightTactico(icono="ðŸ›¡ï¸", texto="Defensa dÃ©bil: promedia 1.9 goles recibidos", metrica="1.9 goles"),
            InsightTactico(icono="âš¡", texto="Poca capacidad ofensiva: solo 0.95 xG promedio", metrica="0.95 xG"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-06-22", rival="Cerro PorteÃ±o", resultado="0-2", formacion="4-4-2"),
            PartidoResumen(fecha="2026-06-15", rival="Sportivo Trinidense", resultado="1-1", formacion="4-4-2"),
            PartidoResumen(fecha="2026-06-08", rival="Rubio Ã‘u", resultado="0-0", formacion="5-3-2"),
        ],
    },
    "stri": {
        "nombre": "Sportivo Trinidense",
        "escudo": "/sportivo-trinidense-logo-footylogos.png",
        "formacion_principal": "4-4-2",
        "formaciones_disponibles": ["4-4-2", "4-3-3", "3-5-2"],
        "jugadores": [
            JugadorTactico(id="stri_1", nombre="Pedro Sarabia", posicion="POR", numero=1, rating=6.7, x=0.5, y=0.95),
            JugadorTactico(id="stri_2", nombre="Marcos Medina", posicion="LD", numero=2, rating=6.6, x=0.85, y=0.75),
            JugadorTactico(id="stri_3", nombre="RaÃºl MartÃ­nez", posicion="DFC", numero=3, rating=6.8, x=0.65, y=0.8),
            JugadorTactico(id="stri_4", nombre="Carlos Gamarra", posicion="DFC", numero=4, rating=6.7, x=0.35, y=0.8),
            JugadorTactico(id="stri_5", nombre="Sergio Arias", posicion="LI", numero=6, rating=6.5, x=0.15, y=0.75),
            JugadorTactico(id="stri_6", nombre="Diego Vargas", posicion="MD", numero=7, rating=6.7, x=0.85, y=0.5),
            JugadorTactico(id="stri_7", nombre="Jorge Espinoza", posicion="MC", numero=5, rating=6.8, x=0.65, y=0.55),
            JugadorTactico(id="stri_8", nombre="RaÃºl Torres", posicion="MC", numero=8, rating=6.7, x=0.35, y=0.55),
            JugadorTactico(id="stri_9", nombre="Santiago Ocampos", posicion="MI", numero=11, rating=6.6, x=0.15, y=0.5),
            JugadorTactico(id="stri_10", nombre="Brian Mendoza", posicion="DC", numero=9, rating=6.9, x=0.55, y=0.25),
            JugadorTactico(id="stri_11", nombre="Arnaldo GonzÃ¡lez", posicion="DC", numero=10, rating=6.8, x=0.45, y=0.25),
        ],
        "stats": EstadisticasEquipo(xg=1.35, posesion=47.0, tiros_puerta=4.1, pases_completados=75.5, duelos_ganados=53.0, corners=4.5),
        "tendencias": [
            InsightTactico(icono="ðŸ“ˆ", texto="MejorÃ­a notable: 4 victorias en Ãºltimos 6", metrica="4 victorias"),
            InsightTactico(icono="âš½", texto="Brian Mendoza: 8 goles en temporada", metrica="8 goles"),
            InsightTactico(icono="ðŸŸï¸", texto="Invicto en 4 partidos en el MartÃ­n Torres", metrica="4 partidos"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-07-10", rival="Olimpia", resultado="2-2", formacion="4-4-2"),
            PartidoResumen(fecha="2026-07-03", rival="Nacional", resultado="1-0", formacion="4-4-2"),
            PartidoResumen(fecha="2026-06-28", rival="Recoleta", resultado="2-1", formacion="4-3-3"),
        ],
    },
    "tembet": {
        "nombre": "Tembetary",
        "escudo": "/club-atletico-tembetary-logo-footylogos.png",
        "formacion_principal": "5-3-2",
        "formaciones_disponibles": ["5-3-2", "4-4-2", "3-5-2"],
        "jugadores": [
            JugadorTactico(id="tembet_1", nombre="Juan GonzÃ¡lez", posicion="POR", numero=1, rating=6.4, x=0.5, y=0.95),
            JugadorTactico(id="tembet_2", nombre="Pedro Torales", posicion="DFD", numero=2, rating=6.3, x=0.9, y=0.75),
            JugadorTactico(id="tembet_3", nombre="Marcos Paredes", posicion="DFC", numero=3, rating=6.5, x=0.7, y=0.8),
            JugadorTactico(id="tembet_4", nombre="Carlos BenÃ­tez", posicion="DFC", numero=4, rating=6.4, x=0.5, y=0.82),
            JugadorTactico(id="tembet_5", nombre="RaÃºl BenÃ­tez", posicion="DFC", numero=5, rating=6.3, x=0.3, y=0.8),
            JugadorTactico(id="tembet_6", nombre="Sergio Amarilla", posicion="DFI", numero=6, rating=6.2, x=0.1, y=0.75),
            JugadorTactico(id="tembet_7", nombre="Diego GonzÃ¡lez", posicion="MC", numero=7, rating=6.6, x=0.65, y=0.55),
            JugadorTactico(id="tembet_8", nombre="Jorge MartÃ­nez", posicion="MC", numero=8, rating=6.5, x=0.5, y=0.6),
            JugadorTactico(id="tembet_9", nombre="Fernando Medina", posicion="MC", numero=10, rating=6.7, x=0.35, y=0.55),
            JugadorTactico(id="tembet_10", nombre="Lucas Fleitas", posicion="DC", numero=9, rating=6.8, x=0.55, y=0.25),
            JugadorTactico(id="tembet_11", nombre="Arnaldo Espinoza", posicion="DC", numero=11, rating=6.7, x=0.45, y=0.25),
        ],
        "stats": EstadisticasEquipo(xg=1.08, posesion=42.5, tiros_puerta=3.0, pases_completados=69.8, duelos_ganados=49.0, corners=3.1),
        "tendencias": [
            InsightTactico(icono="ðŸ›¡ï¸", texto="Defensa compacta: 5 defensores en formaciÃ³n", metrica="5-3-2"),
            InsightTactico(icono="ðŸ“Š", texto="Promedio mÃ¡s bajo de posesiÃ³n: 42.5%", metrica="42.5%"),
            InsightTactico(icono="âš¡", texto="Juego directo: promedia 3.0 tiros a puerta por partido", metrica="3.0 tiros"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-06-22", rival="3 de Febrero", resultado="1-0", formacion="5-3-2"),
            PartidoResumen(fecha="2026-06-15", rival="General DÃ­az", resultado="0-0", formacion="5-3-2"),
            PartidoResumen(fecha="2026-06-08", rival="Deportivo CapiatÃ¡", resultado="1-1", formacion="4-4-2"),
        ],
    },
    "recol": {
        "nombre": "Recoleta FC",
        "escudo": "https://upload.wikimedia.org/wikipedia/en/4/4e/Deportivo_Recoleta_logo.png",
        "formacion_principal": "4-3-3",
        "formaciones_disponibles": ["4-3-3", "4-4-2"],
        "jugadores": [
            JugadorTactico(id="recol_1", nombre="Marcos AcuÃ±a", posicion="POR", numero=1, rating=6.7, x=0.5, y=0.95),
            JugadorTactico(id="recol_2", nombre="Santiago Amarilla", posicion="LD", numero=2, rating=6.6, x=0.85, y=0.75),
            JugadorTactico(id="recol_3", nombre="RaÃºl MartÃ­nez", posicion="DFC", numero=3, rating=6.8, x=0.65, y=0.8),
            JugadorTactico(id="recol_4", nombre="Carlos Gamarra Jr", posicion="DFC", numero=4, rating=6.7, x=0.35, y=0.8),
            JugadorTactico(id="recol_5", nombre="Pedro Villalba", posicion="LI", numero=6, rating=6.5, x=0.15, y=0.75),
            JugadorTactico(id="recol_6", nombre="Diego MartÃ­nez Jr", posicion="MC", numero=5, rating=6.9, x=0.65, y=0.55),
            JugadorTactico(id="recol_7", nombre="Jorge Espinoza Jr", posicion="MC", numero=8, rating=6.8, x=0.5, y=0.6),
            JugadorTactico(id="recol_8", nombre="RaÃºl Torres Jr", posicion="MC", numero=10, rating=7.0, x=0.35, y=0.55),
            JugadorTactico(id="recol_9", nombre="Santiago Ocampos Jr", posicion="ED", numero=7, rating=6.8, x=0.85, y=0.35),
            JugadorTactico(id="recol_10", nombre="Brian Mendoza Jr", posicion="DC", numero=9, rating=7.1, x=0.5, y=0.25),
            JugadorTactico(id="recol_11", nombre="Arnaldo GonzÃ¡lez Jr", posicion="EI", numero=11, rating=6.7, x=0.15, y=0.35),
        ],
        "stats": EstadisticasEquipo(xg=1.42, posesion=48.2, tiros_puerta=4.3, pases_completados=76.0, duelos_ganados=51.5, corners=4.7),
        "tendencias": [
            InsightTactico(icono="âš½", texto="Brian Mendoza Jr: 7 goles, referente ofensivo", metrica="7 goles"),
            InsightTactico(icono="ðŸ“ˆ", texto="En ascenso: 5 victorias en Ãºltimos 8", metrica="5 victorias"),
            InsightTactico(icono="ðŸŸï¸", texto="Juego ofensivo: promedia 4.3 tiros a puerta", metrica="4.3 tiros"),
        ],
        "ultimos_partidos": [
            PartidoResumen(fecha="2026-07-06", rival="Rubio Ã‘u", resultado="1-0", formacion="4-3-3"),
            PartidoResumen(fecha="2026-06-29", rival="Olimpia", resultado="2-3", formacion="4-3-3"),
            PartidoResumen(fecha="2026-06-22", rival="Sportivo Trinidense", resultado="1-2", formacion="4-4-2"),
        ],
    },
}


# Datos mock para anÃ¡lisis de partidos
PARTIDOS_MOCK = {
    "match_123": {
        "local": {
            "equipo_id": "cerro",
            "nombre": "Cerro PorteÃ±o",
            "formacion": "4-3-3",
            "jugadores": EQUIPOS_MOCK["cerro"]["jugadores"],
        },
        "visitante": {
            "equipo_id": "olimpi",
            "nombre": "Olimpia",
            "formacion": "4-4-2",
            "jugadores": EQUIPOS_MOCK["olimpi"]["jugadores"],
        },
        "stats": StatsComparativa(
            local=EQUIPOS_MOCK["cerro"]["stats"],
            visitante=EQUIPOS_MOCK["olimpi"]["stats"],
        ),
        "prediccion_ia": PrediccionIA(
            gana_local=0.45,
            empate=0.28,
            gana_visitante=0.27,
            confianza="media",
        ),
    },
    "match_124": {
        "local": {
            "equipo_id": "libert",
            "nombre": "Libertad",
            "formacion": "4-2-3-1",
            "jugadores": EQUIPOS_MOCK["libert"]["jugadores"],
        },
        "visitante": {
            "equipo_id": "guaran",
            "nombre": "GuaranÃ­",
            "formacion": "4-3-3",
            "jugadores": EQUIPOS_MOCK["guaran"]["jugadores"],
        },
        "stats": StatsComparativa(
            local=EQUIPOS_MOCK["libert"]["stats"],
            visitante=EQUIPOS_MOCK["guaran"]["stats"],
        ),
        "prediccion_ia": PrediccionIA(
            gana_local=0.52,
            empate=0.25,
            gana_visitante=0.23,
            confianza="alta",
        ),
    },
}


class TacticoService:
    @staticmethod
    async def get_equipo(equipo_id: str) -> EquipoTactico | None:
        if equipo_id not in EQUIPOS_MOCK:
            return None
        data = EQUIPOS_MOCK[equipo_id]
        return EquipoTactico(
            equipo_id=equipo_id,
            nombre=data["nombre"],
            escudo=data["escudo"],
            formacion_principal=data["formacion_principal"],
            formaciones_disponibles=data["formaciones_disponibles"],
            jugadores=data["jugadores"],
            stats=data["stats"],
            tendencias=data["tendencias"],
            ultimos_partidos=data["ultimos_partidos"],
        )

    @staticmethod
    async def get_partido(partido_id: str) -> AnalisisPartido | None:
        if partido_id not in PARTIDOS_MOCK:
            return None
        data = PARTIDOS_MOCK[partido_id]
        return AnalisisPartido(
            partido_id=partido_id,
            local=EquipoPartidoTactico(**data["local"]),
            visitante=EquipoPartidoTactico(**data["visitante"]),
            stats=data["stats"],
            prediccion_ia=data["prediccion_ia"],
        )

    @staticmethod
    async def get_equipos_disponibles() -> list[dict]:
        return [
            {
                "id": eid,
                "nombre": data["nombre"],
                "escudo": data["escudo"],
                "formacion": data["formacion_principal"],
            }
            for eid, data in EQUIPOS_MOCK.items()
        ]
