"""add club fields and temporada

Revision ID: 6fbc92ce284a
Revises: e89293bef80c
Create Date: 2026-07-07 17:06:46.313211
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fbc92ce284a'
down_revision: Union[str, None] = 'e89293bef80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('clubes', sa.Column('sitio_web', sa.String(length=500), nullable=True))
    op.add_column('clubes', sa.Column('descripcion', sa.String(length=2000), nullable=True))
    op.add_column('clubes', sa.Column('titulos_liga', sa.Integer(), nullable=True))
    op.add_column('clubes', sa.Column('titulos_info', sa.JSON(), nullable=True))
    op.add_column('partidos', sa.Column('temporada', sa.String(length=20), nullable=True))
    op.execute("UPDATE clubes SET sitio_web='', descripcion='', titulos_liga=0, titulos_info='[]'::json")
    op.execute("UPDATE partidos SET temporada='' WHERE temporada IS NULL")
    op.alter_column('clubes', 'sitio_web', nullable=False)
    op.alter_column('clubes', 'descripcion', nullable=False)
    op.alter_column('clubes', 'titulos_liga', nullable=False)
    op.alter_column('clubes', 'titulos_info', nullable=False)
    op.alter_column('partidos', 'temporada', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partidos', 'temporada')
    op.drop_column('clubes', 'titulos_info')
    op.drop_column('clubes', 'titulos_liga')
    op.drop_column('clubes', 'descripcion')
    op.drop_column('clubes', 'sitio_web')
    # ### end Alembic commands ###
