"""initial tables

Revision ID: e89293bef80c
Revises: 
Create Date: 2026-07-07 17:05:49.698204
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e89293bef80c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('apodo', sa.String(length=100), nullable=False),
    sa.Column('colores', sa.JSON(), nullable=False),
    sa.Column('estadio', sa.String(length=150), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('fundacion', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('escudo', sa.String(length=500), nullable=False),
    sa.Column('camiseta', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.String(length=200), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('partidos',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('torneo', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('jornada', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.String(length=50), nullable=False),
    sa.Column('visitante_id', sa.String(length=50), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=True),
    sa.Column('goles_visitante', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['local_id'], ['clubes.id'], ),
    sa.ForeignKeyConstraint(['visitante_id'], ['clubes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabla_posiciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('torneo', sa.String(length=100), nullable=False),
    sa.Column('jornada', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.String(length=50), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('pj', sa.Integer(), nullable=False),
    sa.Column('pg', sa.Integer(), nullable=False),
    sa.Column('pe', sa.Integer(), nullable=False),
    sa.Column('pp', sa.Integer(), nullable=False),
    sa.Column('gf', sa.Integer(), nullable=False),
    sa.Column('gc', sa.Integer(), nullable=False),
    sa.Column('dg', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes_chat',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('partido_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_chat_partido_id'), 'mensajes_chat', ['partido_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('partido_id', sa.String(length=50), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=False),
    sa.Column('goles_visitante', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'partido_id', name='uq_user_partido')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_index(op.f('ix_mensajes_chat_partido_id'), table_name='mensajes_chat')
    op.drop_table('mensajes_chat')
    op.drop_table('tabla_posiciones')
    op.drop_table('push_subscriptions')
    op.drop_table('partidos')
    op.drop_table('users')
    op.drop_table('clubes')
    # ### end Alembic commands ###
